import { NextResponse } from "next/server";
import { z } from "zod";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { mintPickupToken, pickupQrPayload } from "@/lib/pickup";
import { recordJobEvent } from "@/lib/jobs";

type Params = { params: Promise<{ id: string }> };

const Schema = z.object({
  /** Default MAKER_TO_CREATOR — creator displays the code; maker scans/types
   *  it. Pass CREATOR_TO_MAKER for the reverse fallback. */
  direction: z.enum(["MAKER_TO_CREATOR", "CREATOR_TO_MAKER"]).default("MAKER_TO_CREATOR"),
});

export async function POST(req: Request, { params }: Params) {
  const session = await auth();
  if (!session?.user?.id)
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  const { id } = await params;

  const job = await prisma.job.findUnique({ where: { id } });
  if (!job) return NextResponse.json({ error: "not found" }, { status: 404 });

  const profile = await prisma.makerProfile.findUnique({
    where: { userId: session.user.id },
  });
  const isCreator = job.creatorId === session.user.id;
  const isAssignedMaker = profile && job.assignedMakerId === profile.id;
  if (!isCreator && !isAssignedMaker)
    return NextResponse.json({ error: "forbidden" }, { status: 403 });

  if (!["READY_FOR_PICKUP", "IN_PROGRESS", "ASSIGNED"].includes(job.status)) {
    return NextResponse.json(
      { error: `cannot mint pickup token from status ${job.status}` },
      { status: 400 }
    );
  }

  const parsed = Schema.safeParse(await req.json().catch(() => ({})));
  if (!parsed.success) return NextResponse.json({ error: "invalid body" }, { status: 400 });

  // MAKER_TO_CREATOR may only be minted by the maker (canonical flow).
  // CREATOR_TO_MAKER reverse fallback only by the creator.
  if (parsed.data.direction === "MAKER_TO_CREATOR" && !isAssignedMaker) {
    return NextResponse.json({ error: "only the maker can mint this direction" }, { status: 403 });
  }
  if (parsed.data.direction === "CREATOR_TO_MAKER" && !isCreator) {
    return NextResponse.json({ error: "only the creator can mint this direction" }, { status: 403 });
  }

  const token = await mintPickupToken({ jobId: id, direction: parsed.data.direction });
  await recordJobEvent({
    jobId: id,
    actor: isCreator ? "creator" : "maker",
    actorId: session.user.id,
    kind: "pickup_minted",
    body: parsed.data.direction === "MAKER_TO_CREATOR"
      ? "Pickup code regenerated."
      : "Reverse pickup code generated by creator.",
    data: {
      direction: token.direction,
      expiresAt: token.expiresAt.toISOString(),
    },
  });
  return NextResponse.json({
    token: {
      code: token.code,
      qr: pickupQrPayload(token.code),
      direction: token.direction,
      expiresAt: token.expiresAt.toISOString(),
    },
  });
}
